spring:
  datasource:
    url: ${postgresql://postgres:muNkccGyVPZGpinjdJENDZyoiWXWqKdR@postgres.railway.internal:5432/railway}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql

server:
  port: 8081
