server:
  port: 8081
 
spring:
  datasource:
    url: ${jdbc:postgresql://dpg-d7kpodpkh4rs73fbr7b0-a.virginia-postgres.render.com/aula_310b?sslmode=require}
    username: ${postgressql}
    password: ${MvSnbUZUmygIc33jHA1kOGWjyD3OrlCA}
    driver-class-name: org.postgresql.Driver
 
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql
